### PR TITLE
Adding Michelin star restaurants

### PR DESCRIPTION
**Pull request by bkowshik**
From https://en.wikipedia.org/wiki/List_of_Michelin_3-star_restaurants

> Michelin stars are a rating system used by the red Michelin Guide to grade restaurants on their quality. According to the Guide, one star signifies "a very good restaurant", two stars are "excellent cooking that is worth a detour", and three stars mean "exceptional cuisine that is worth a special journey".[2] The listing of starred restaurants is updated once a year.

etoile_michelin-1 svg

Running the following Wikidata query resulted in `550` restaurants with Michelin star.

- http://tinyurl.com/h5elx3r

```
SELECT ?item ?itemLabel ?_coordinate_location ?_countryLabel WHERE {
  ?item wdt:P166 wd:Q20824563.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  OPTIONAL { ?item wdt:P625 ?_coordinate_location. }
  OPTIONAL { ?item wdt:P17 ?_country. }
}
```

- `466` out of the `550` restaurants (approx 85%) have a geo-location on Wikidata
- The number of restaurants in the Netherlands, about `250` dominate the list

screen shot 2017-02-27 at 4 08 02 pm

There are a lot more restaurants listed on Wikipedia pages below which we could add if required:
- [List of Michelin 3-star restaurants](https://en.wikipedia.org/wiki/List_of_Michelin_3-star_restaurants)
- [List of Michelin starred restaurants in San Francisco](https://en.wikipedia.org/wiki/List_of_Michelin_starred_restaurants_in_the_San_Francisco_Bay_Area)

---

cc: @planemad @geohacker

### CODE REVIEW

**Comment by bkowshik** [comment]
cc: @amishas157

**Comment by bkowshik** [comment]
Queried `overpass-turbo` to convert from Wikidata IDs to OSM IDs. But, the hit rate is very low, only 33 out of 550 (`6%`) were present in OpenStreetMap with the corresponding Wikidata tag.

- [Google doc with Michelin Star restaurants](https://docs.google.com/spreadsheets/d/1R7J3sct4qHpNlC65KzIkQ7eSCBMo9RdmgmNT6uI5LkU/edit?usp=sharing)

**Comment by bkowshik** [comment]
A majority of restaurants are of geometry type `node`. But, there are a few, `5` in the above list of `33` restaurants have are mapped as `way`. Ex:

screen shot 2017-02-27 at 6 34 31 pm

**Comment by amishas157** [comment]
Working on distance based approach to get landmarks list [here](https://github.com/osmlab/osm-landmarks/tree/distance-based-approach).

- Geographical distance difference: 100m
- Levenshtein difference among name: 0 - 100

Here are the  [results](https://docs.google.com/a/mapbox.com/spreadsheets/d/1_YA0YjUKi1OTkXyGUQC-azCNG8Reo57jRBPmx7Uk5mI/edit?usp=sharing) . This matching was done for wikidata items which have location property.
Out of 466, 130 matches (0 levenshtein distance) look exact.

cc @bkowshik

**Comment by bkowshik** [comment]
Closing this in favor of: https://github.com/osmlab/osm-landmarks/pull/7

**Pull request closed without merging**
